import { useState } from 'react'                                                                                                                                                                                                                
import axios from 'axios'                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                
function RegisterPage() {                                                                                                                                                                                                                       
  const [email, setEmail] = useState('')                                                                                                                                                                                                        
  const [password, setPassword] = useState('')                                                                                                                                                                                                  
  const [userType, setUserType] = useState('')                                                                                                                                                                                                  
  const [companyName, setCompanyName] = useState('')                                                                                                                                                                                            
  const [companyLogo, setCompanyLogo] = useState('')                                                                                                                                                                                            
                                                                                                                                                                                                                                                
  const handleSubmit = async (e) => {                                                                                                                                                                                                             
    e.preventDefault()                                                                                                                                                                                                                          
    try {                                                                                                                                                                                                                                       
      const response = await axios.post('https://job-backend-8rmo.onrender.com/users/register', { email, password, userType })                                                                                                                                  
      if (response.data.userType === 'student') {                                                                                                                                                                                               
        console.log('You have been credited with 300 Rupees.')                                                                                                                                                                                  
      } else if (response.data.userType === 'company') {                                                                                                                                                                                        
        console.log('You have been credited with 200 Rupees.')                                                                                                                                                                                  
      }                                                                                                                                                                                                                                         
      console.log(response.data)                                                                                                                                                                                                                
    } catch (error) {                                                                                                                                                                                                                           
      console.error(error)                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                           
  }                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                
  return (                                                                                                                                                                                                                                      
    <div>                                                                                                                                                                                                                                       
      <h1>Register</h1>                                                                                                                                                                                                                         
      <form onSubmit={handleSubmit}>                                                                                                                                                                                                            
        <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" required />                                                                                                                            
        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" required />                                                                                                                
        <select value={userType} onChange={(e) => setUserType(e.target.value)} required>                                                                                                                                                        
          <option value="">Select user type</option>                                                                                                                                                                                            
          <option value="student">Student</option>                                                                                                                                                                                              
          <option value="company">Company</option>                                                                                                                                                                                              
        </select>                                                                                                                                                                                                                               
        {userType === 'company' && (                                                                                                                                                                                                            
          <>                                                                                                                                                                                                                                    
            <input type="text" value={companyName} onChange={(e) => setCompanyName(e.target.value)} placeholder="Company Name" required />                                                                                                      
            <input type="text" value={companyLogo} onChange={(e) => setCompanyLogo(e.target.value)} placeholder="Company Logo URL" required />                                                                                                  
          </>                                                                                                                                                                                                                                   
        )}                                                                                                                                                                                                                                      
        <button type="submit">Register</button>                                                                                                                                                                                                 
      </form>                                                                                                                                                                                                                                   
    </div>                                                                                                                                                                                                                                      
  )                                                                                                                                                                                                                                             
}                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                
export default RegisterPage;